<?php
	/*---Include External Styles & Scripts---*/
	function resources() {
		wp_enqueue_style('style', get_template_directory_uri() . '/style.css');
		wp_enqueue_script('script', get_template_directory_uri() . '/script.js');
	}
	
	add_action('wp_enqueue_scripts', 'resources');



	/*---Allow Pages to have Featured Images---*/
	add_theme_support('post-thumbnails', array('post', 'page'));



	/*---Header Widgets---*/
	function logo_widget_init() {
		register_sidebar(array(
			'name' => __('Site Logo', 'bard'),
			'id' => 'header_widget_1',
			'description' => __('Add your sites logo here.', 'bard')
		));
	}

	add_action('widgets_init', 'logo_widget_init' );

	function title_widget_init() {
		register_sidebar(array(
			'name' => __('Site Title', 'bard'),
			'id' => 'header_widget_2',
			'description' => __('Add your sites title here.', 'bard')
		));
	}

	add_action('widgets_init', 'title_widget_init' );

	function subtitle_widget_init() {
		register_sidebar(array(
			'name' => __('Site Subtitle', 'bard'),
			'id' => 'header_widget_3',
			'description' => __('Add your sites subtitle here.', 'bard')
		));
	}

	add_action('widgets_init', 'subtitle_widget_init');

	function mobile_icon_widget_init() {
		register_sidebar(array(
			'name' => __('Mobile Icon', 'bard'),
			'id' => 'header_widget_4',
			'description' => __('Please paste your selected mobile icon in here e.g <img src="icon_url" alt="Mobile Icon" />', 'bard')
		));
	}

	add_action('widgets_init', 'mobile_icon_widget_init');



	/*---Category/Sidebar Widget Function---*/
	function category_widget_init() {
		register_sidebar(array(
			'name' => __('Category Navigation', 'bard'),
			'id' => 'category_widget',
			'description' => __('Please insert your custom category menu here.', 'bard')
		));
	}

	add_action('widgets_init', 'category_widget_init');



	/*---Footer Widget Function---*/
	function footnote_widget_init() {
		register_sidebar(array(
			'name' => __('Footnote', 'bard'),
			'id' => 'footer_widget_1',
			'description' => __('Add your sites footnote here.', 'bard')
		));
	}

	add_action('widgets_init', 'footnote_widget_init');

	function disclaimer_widget_init() {
		register_sidebar(array(
			'name' => __('Author & Disclaimer', 'bard'),
			'id' => 'footer_widget_2',
			'description' => __('Add main blog author and disclaimer here.', 'bard')
		));
	}

	add_action('widgets_init', 'disclaimer_widget_init');

	function developer_widget_init() {
		register_sidebar(array(
			'name' => __('Developed By', 'bard'),
			'id' => 'footer_widget_3',
			'description' => __('Add a link to theme developer here.', 'bard')
		));
	}

	add_action('widgets_init', 'developer_widget_init');



	/*---Write PHP Within Text Widgets---*/
	function text_widget_php_filter($html) {
		if (strpos($html, "<"."?php") !== false) {
			ob_start();
			eval("?".">".$html);
			$html = ob_get_contents();
			ob_end_clean();
		}

		return $html;
	}

	add_filter('widget_text', 'text_widget_php_filter', 100);



	/*---Menu Function---*/
	function wpb_custom_new_menu() {
		register_nav_menus(
			array(
				'primary_menu' => __('Primary Menu'),
				'secondary_menu' => __('Secondary Menu')
			)
		);
	}

	add_action( 'init', 'wpb_custom_new_menu' );



	/*---Poem of the Month Meta Box for Pages---*/
	/*---Generated by the WordPress Meta Box generator---*/
	/*---at http://jeremyhixon.com/tool/wordpress-meta-box-generator---*/
	/*---Usage: poem_of_the_month_get_meta('poem_of_the_month_display_poem_of_the_month_on_this_page');---*/
	function poem_of_the_month_get_meta($value) {
		global $post;

		$field = get_post_meta($post->ID, $value, true);

		if (! empty($field)) {
			return is_array($field) ? stripslashes_deep($field) : stripslashes(wp_kses_decode_entities($field));
		} else {
			return false;
		}
	}

	function poem_of_the_month_add_meta_box() {
		add_meta_box(
			'poem_of_the_month-poem-of-the-month',
			__( 'Poem of the Month', 'poem_of_the_month' ),
			'poem_of_the_month_html',
			'page',
			'advanced',
			'core'
		);
	}

	add_action('add_meta_boxes', 'poem_of_the_month_add_meta_box');

	function poem_of_the_month_html($post) {
		wp_nonce_field('_poem_of_the_month_nonce', 'poem_of_the_month_nonce'); ?>

		<p>
			<input type="checkbox" name="poem_of_the_month_display_poem_of_the_month_on_this_page" id="poem_of_the_month_display_poem_of_the_month_on_this_page" value="display-poem-of-the-month-on-this-page" <?php echo ( poem_of_the_month_get_meta( 'poem_of_the_month_display_poem_of_the_month_on_this_page' ) === 'display-poem-of-the-month-on-this-page' ) ? 'checked' : ''; ?>>
			<label for="poem_of_the_month_display_poem_of_the_month_on_this_page"><?php _e( 'Display Poem of the Month on this Page', 'poem_of_the_month' ); ?></label>
		</p>
	<?php }

	function poem_of_the_month_save($post_id) {
		if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) return;
		if (! isset($_POST['poem_of_the_month_nonce']) || ! wp_verify_nonce($_POST['poem_of_the_month_nonce'], '_poem_of_the_month_nonce')) return;
		if (! current_user_can('edit_post', $post_id)) return;

		if (isset($_POST['poem_of_the_month_display_poem_of_the_month_on_this_page']))
			update_post_meta($post_id, 'poem_of_the_month_display_poem_of_the_month_on_this_page', esc_attr($_POST['poem_of_the_month_display_poem_of_the_month_on_this_page']));
		else
			update_post_meta($post_id, 'poem_of_the_month_display_poem_of_the_month_on_this_page', null);
	}

	add_action('save_post', 'poem_of_the_month_save');



	function get_category_by_url($url) {
    foreach( (get_the_category()) as $category) {
        if ( get_category_link($category->cat_ID) == $url )
            return $category->slug;
    }
    return false;
}